# Zombienet setup designed to test the runtime upgrade and its migration by refering to an old chain-spec.json.
#
# The upgrade can be done via polkadot-js/apps:
#   1.  Create chain-spec with the old collator-node containing our current production network with:
#       `./scripts/dump_wasm_state_and_spec.sh <desired_chain>` and copy it into this directory.
#   2.  Create new was runtime with the new collator with `./scripts/dump_wasm_state_and_spec.sh <desired_chain>`
#   3.  Migrate storage from production chain to local setup with https://github.com/ajuna-network/Ajuna.StorageTools/blob/main/Ajuna.StorageTools/Program.cs
#   4.  Call: `sudo.call(parachainSystem.(authorizeUgrade(...))`
#   5.  Call: `parachainSystem.enactAuthorizedUpgrade()`
#   6.  Wait until the code is applied.

[settings]
timeout = 10000

[relaychain]
default_command = "~/bin/polkadot"
default_args = [ "-lparachain=debug,xcm=trace" ]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9999

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9988

[[relaychain.nodes]]
name = "charlie"
validator = true
ws_port = 9977

[[parachains]]
id = 2000
addToGenesis = true
cumulus_based = true

[parachains.collator]
name = "bajun-collator"
# This should ideally be the old collator as this is used
# to build the modified chain-spec.
command = "~/bin/bajun-node-v500"

[[parachains.collators]]
name = "bajun-collator-1"
validator = true
command = "~/bin/bajun-node-v600-rc1"
args = ["-lxcm=trace,runtime=debug"]
ws_port = 9954

[[parachains.collators]]
name = "bajun-collator-2"
validator = true
command = "~/bin/bajun-node-v600-rc1"
args = ["-lxcm=trace,runtime=debug"]
ws_port = 9955


[[parachains.collators]]
name = "bajun-collator-3"
validator = true
command = "~/bin/bajun-node-v600-rc1"
args = ["-lxcm=trace,runtime=debug"]
ws_port = 9956